defaults: &defaults
  working_directory: ~/circleci-workspace

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:10
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: Save version number
          command: echo "v$CIRCLE_BUILD_NUM" > app-version.txt
      - restore_cache:
          keys:
          - dependencies-v1-{{ checksum "yarn.lock" }}
          - dependencies-v1-
      - run: 
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: mkdir -p ${TEST_RESULTS} && yarn test ${TEST_RESULTS}/test_results.txt
      - store_test_results:
          path: /tmp/test-results
      - setup_remote_docker
      - run: 
          name: Build with Docker
          command: |
            TAG=v$CIRCLE_BUILD_NUM
            docker build --build-arg APP_VERSION=$TAG -t $DOCKER_USER/${CIRCLE_PROJECT_REPONAME}:$TAG -t $DOCKER_USER/${CIRCLE_PROJECT_REPONAME}:latest .
      - run:
          name: Upload to Docker Hub
          command: |
            TAG=v$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_USER/${CIRCLE_PROJECT_REPONAME}:$TAG
            docker push $DOCKER_USER/${CIRCLE_PROJECT_REPONAME}:latest
      - run:
          name: "Get SHA of latest docker build"
          command: |
            DOCKER_HUB_TOKEN=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$DOCKER_USER/$CIRCLE_PROJECT_REPONAME:pull" | jq -r '.token')
            curl -H "Authorization: Bearer $DOCKER_HUB_TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://registry.hub.docker.com/v2/$DOCKER_USER/$CIRCLE_PROJECT_REPONAME/manifests/latest | jq -r '.config.digest' > image_sha.txt
            cat image_sha.txt
      - save_cache:
          paths:
            - app-version.txt
          key: version-v1-{{ checksum "image_sha.txt" }}

  deploy-kellenforthewin:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f6:59:4f:20:95:32:55:c6:95:fc:43:5e:76:aa:ac:f4"
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "bash ~/kspw-kubernetes/bin/deploy.sh $DOCKER_USER $CIRCLE_PROJECT_REPONAME"

  deploy-kellenschmidtcom:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "86:20:9b:53:2d:a6:f6:14:4e:02:64:27:87:d9:d6:b5"
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "bash ~/kspw-kubernetes/bin/deploy.sh $DOCKER_USER $CIRCLE_PROJECT_REPONAME"

  publish-github-release:
    <<: *defaults
    docker:
      - image: cibuilds/github:0.10
    steps:
      - run:
          name: "Get SHA of latest docker build"
          command: |
            DOCKER_HUB_TOKEN=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$DOCKER_USER/$CIRCLE_PROJECT_REPONAME:pull" | jq -r '.token')
            curl -H "Authorization: Bearer $DOCKER_HUB_TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://registry.hub.docker.com/v2/$DOCKER_USER/$CIRCLE_PROJECT_REPONAME/manifests/latest | jq -r '.config.digest' > image_sha.txt
            cat image_sha.txt
      - restore_cache:
          keys:
          - version-v1-{{ checksum "image_sha.txt" }}
      - run:
          name: "Move cached files to working directory"
          command: |
            mv /home/circleci/circleci-workspace/app-version.txt .
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat app-version.txt)
            ARTIFACT_DIR=artifacts
            ARTIFACT_NAME=dist_$VERSION
            mkdir $ARTIFACT_DIR
            mv app-version.txt $ARTIFACT_DIR
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 -delete $VERSION $ARTIFACT_DIR

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: kellenforthewin
          filters:
            branches:
              only: dev
      - deploy-kellenforthewin:
          requires:
            - build
          context: kellenforthewin
          filters:
            branches:
              only: dev
      - publish-github-release:
          context: kellenschmidt.com
          filters:
            branches:
              only: master
      - deploy-kellenschmidtcom:
          context: kellenschmidt.com
          filters:
            branches:
              only: master
